on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APKs
        uses: ./.github/workflows/kivy
        with:
          python-version: 3.8
          work-dir: .
          buildozer-cmd: buildozer -v android debug

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: ./bin/*.apk
